name = "FisherPlot"
uuid = "a6a81055-8810-4a7f-bad9-3c67194ad2e1"
authors = ["Marco Bonici <bonici.marco@gmail.com>"]
version = "0.1.1"

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
LaTeXStrings = "1"
Makie = "0.20"
julia = "1.6"
